

project:
  type: website
  output-dir: docs

website:
  title: "elevenw11se.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Data Viz"  
        menu:
          - href: Netflix Shows And Movies Analysis.qmd
            text: Netflix Shows And Movies Analysis
          - href: Premier_League_Match_Analysis.qmd
            text: Premier League Match Analysis
          - href: SAFI_Data_Survey_Analysis.qmd
            text: SAFI Data Survey Analysis
          - href: Project_3.qmd
            text: Birth Count Analysis
          - href: SQL_WAI_Analysis.qmd
            text: SQL WAI Analysis
    
      
        


format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    
    
    



