project:
  type: website
  output-dir: docs

website:
  title: "elevenw11se.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Premier League Match Analysis.qmd
        text: Premier League Match Analysis
      - href: SAFI Data Survey Analysis.qmd
        text: SAFI Data Survey Analysis
      - href: Project 3.qmd
        text: Birth Count Analysis
      - href: SQL WAI Analysis.qmd
        text: SQL WAI Analysis
    
      
        


format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    
    
    



