project:
  type: website
  output-dir: docs

website:
  title: "elevenw11se.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Premier League Match Analysis.qmd
      - SAFI Data Survey Analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    
    



