project:
  type: website
  output-dir: docs

website:
  title: "elevenw11se.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Premier League Match Analysis.qmd
      - SAFI Data Survey Analysis.qmd
      - href: Project 3.qmd
        text: Birth Count Analysis
      - href: SQL WAI Analysis.qmd
        text: SQL WAI Analysis


format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    
    
    



